import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import routes from './routes/todoRoutes.js';
import {prisma} from './config/prisma.js';
const app=express(),port=Number(process.env.PORT)||4000;
app.use(cors({origin:process.env.CLIENT_ORIGIN||'http://localhost:5173'}));
app.use(express.json({limit:'1mb'}));
app.get('/api/health',(req,res)=>res.json({status:'ok',service:'TaskFlow API'}));
app.use('/api/todos',routes);
app.use((req,res)=>res.status(404).json({error:'Route not found'}));
app.use((err,req,res,next)=>{console.error(err);if(err.code==='P2025')return res.status(404).json({error:'Todo not found'});res.status(500).json({error:'Internal server error'});});
const server=app.listen(port,()=>console.log(`TaskFlow API: http://localhost:${port}`));
for(const signal of ['SIGINT','SIGTERM'])process.on(signal,()=>server.close(async()=>{await prisma.$disconnect();process.exit(0);}));
